{% set name = "streamlit" %}
{% set version = "1.41.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: 6626d32b098ba1458b71eebdd634c62af2dd876380e59c4b6a1e828a39d62d69

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - streamlit = streamlit.web.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - altair >=4.0,<6
    - blinker >=1.0.0,<2
    - cachetools >=4.0,<6
    - click >=7.0,<9
    - gitpython >=3.0.7,<4,!=3.1.19
    - numpy >=1.23,<3
    - packaging >=20,<25
    - pandas >=1.4.0,<3
    - pillow >=7.1.0,<12
    - protobuf >=3.20,<6
    - pyarrow >=7.0
    - pydeck >=0.8.0b4,<1
    - python >={{ python_min }}
    - python-dateutil >=2.7.3, <3
    - requests >=2.27,<3
    - rich >=10.14.0,<14
    - tenacity >=8.1.0,<10
    - toml >=0.10.1,<2
    - tornado >=6.0.3,<7
    - typing_extensions >=4.3.0,<5
    - tzlocal >=1.1,<6
    - watchdog >=2.1.5,<7

test:
  imports:
    - streamlit
    - streamlit.proto.RootContainer_pb2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://streamlit.io
  summary: A faster way to build and share data apps
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vdonato
    - raybellwaves
    - kmcgrady
    - jroes
    - xhochy
