{% set name = "streamlit" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: 9479d623dd4bec1fc7bd27e85d5012672351210e640889022ee7b4631c4efb2c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streamlit = streamlit.cli:main

requirements:
  host:
    - pip
    - python >=3.7
    - pipenv
  run:
    - altair >=3.2.0
    - attrs
    - blinker
    - cachetools >=4.0
    - click >=7.0, <8.1
    - gitpython !=3.1.19
    - importlib-metadata >=1.4
    - numpy
    - packaging
    - pandas >=0.21.0
    - pillow >=6.2.0
    - protobuf >=3.12, <4
    - pyarrow
    - pydeck >=0.1.dev5
    - pympler >=0.9
    - python >=3.6
    - python-dateutil
    - requests
    - toml
    - tornado >=5.0
    - typing_extensions
    - tzlocal
    - validators
    - watchdog

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: The fastest way to build data apps in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
