{% set name = "streamlit" %}
{% set version = "0.71.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: cdefc723b48129642564bc0f9be8a123d9b2e895a03e39d4dc478ef66f0bf061

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pipenv
  run:
    - altair >=3.2.0
    - astor
    - base58
    - blinker
    - boto3
    - botocore >=1.13.44
    - cachetools >=4.0
    - click >=7.0
    - enum-compat
    - gitpython
    - numpy
    - packaging
    - pandas >=0.21.0
    - pillow >=6.2.0
    - protobuf >=3.6.0
    - pyarrow
    - pydeck >=0.1.dev5
    - python >=3.6
    - python-dateutil
    - requests
    - toml
    - tornado >=5.0
    - tzlocal
    - validators
    - watchdog

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: The fastest way to build data apps in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
