{% set name = "streamlit" %}
{% set version = "1.24.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: fd5f0b64798e9706364408fb589b77595314a6315d13b2d750b963c7ae97f362

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streamlit = streamlit.web.cli:main

requirements:
  host:
    - pip
    - python >=3.8, !=3.9.7
  run:
    - altair >=3.2.0,<6
    - blinker >=1.0.0,<2
    - cachetools >=4.0,<6
    - click >=7.0,<9
    - gitpython >=3,<4,!=3.1.19
    - importlib-metadata >=1.4,<7
    - numpy >=1,<2
    - packaging >=14.1,<24
    - pandas <3,>=0.25
    - pillow >=6.2.0,<10
    - protobuf >=3.20,<5
    - pyarrow >=4.0
    - pydeck >=0.1.dev5,<1
    - pympler >=0.9,<2
    - python >=3.8
    - python-dateutil >=2,<3
    - requests >=2.4,<3
    - rich >=10.11.0,<14
    - tenacity <9,>=8.0.0
    - toml <2
    - tornado >=6.0.3,<7
    - typing_extensions >=4.0.1,<5
    - tzlocal >=1.1,<5
    - validators >=0.2,<1
    - watchdog

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: A faster way to build and share data apps
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vdonato
    - raybellwaves
    - kmcgrady
    - jroes
    - xhochy
