{% set name = "streamlit" %}
{% set version = "1.32.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: 65bf22e190de973b910c0b127b33d80d31c5275ed891c6fde740de46e5e05323

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streamlit = streamlit.web.cli:main

requirements:
  host:
    - pip
    - python >=3.8, !=3.9.7
  run:
    - altair >=3.2.0,<6
    - blinker >=1.0.0,<2
    - cachetools >=4.0,<6
    - click >=7.0,<9
    - gitpython >=3.0.7, <4, !=3.1.19
    - importlib-metadata >=1.4,<8
    - numpy >=1.19.3, <2
    - packaging >=16.8, <24
    - pandas >=1.3.0, <3
    - pillow >=7.1.0, <11
    - protobuf >=3.20,<5
    - pyarrow >=7.0
    - pydeck >=0.8.0b4, <1
    - python >=3.8
    - python-dateutil >=2.7.3, <3
    - requests >=2.27, <3
    - rich >=10.14.0, <14
    - tenacity <9,>=8.0.0
    - toml >=0.10.1, <2
    - tornado >=6.0.3,<7
    - typing_extensions >=4.1.0, <5
    - tzlocal >=1.1,<6
    - validators >=0.2,<1
    - watchdog >=2.1.5

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: A faster way to build and share data apps
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vdonato
    - raybellwaves
    - kmcgrady
    - jroes
    - xhochy
