{% set name = "streamlit" %}
{% set version = "1.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: eb178dc87d9f01e2be11ee9e4d55f79a678597ece56cacbfe5a9236d768d48da

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streamlit = streamlit.web.cli:main

requirements:
  host:
    - pip
    - python >=3.7, !=3.9.7
  run:
    - altair >=3.2.0
    - blinker >=1.0.0
    - cachetools >=4.0
    - click >=7.0
    - gitpython !=3.1.19
    - importlib-metadata >=1.4
    - numpy
    - packaging >=14.1
    - pandas >=0.21.0
    - pillow >=6.2.0
    - protobuf >=3.12, <4, !=3.20.2
    - pyarrow >=4.0
    - pydeck >=0.1.dev5
    - pympler >=0.9
    - python >=3.7
    - python-dateutil
    - requests >=2.4
    - rich >=10.11.0
    - semver
    - toml
    - tornado >=5.0
    - typing_extensions >=3.10.0.0
    - tzlocal >=1.1
    - validators >=0.2
    - watchdog

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: The fastest way to build data apps in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vdonato
    - raybellwaves
    - kmcgrady
    - jroes
